#!/bin/python
from ui import get_term
from ui import Dashboard
from model.todotxt import TodotxtModel
from model.jira import JiraModel
import sys
from os.path import dirname, join
import asyncio
from asyncio import Queue
import threading
from settings import Settings

term = get_term()

async def main(queue):

    # init
    if len(sys.argv) == 1:
        todofile = "todo.txt"
        donefile = "done.txt"
    elif len(sys.argv) >= 2:
        todofile = sys.argv[1]
        donefile = join(dirname(todofile), "done.txt")

    if len(sys.argv) == 3:
        filter = sys.argv[-1]
    else:
        filter = ".*"

    if todofile == "jira":
        model = JiraModel(Settings.get("jira.instance"), Settings.get("jira.username"), Settings.get("jira.api_token"), Settings.get("jira.jql"))
    else:
        model = TodotxtModel(todofile, donefile)

    dash = Dashboard(model, filter)
    await dash.loop(queue)


if __name__ == "__main__":
    queue = Queue()
    t = threading.Thread(target=term.threaded_inkey, args=[queue])
    t.start()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(queue))

