
COLUMN_WIDTH   = 40
WINDOW_PADDING = 1
WINDOW_MARGIN  = 1
LIST_HIDDEN    = True
TAG_HIDDEN     = True
SUBTAG_HIDDEN  = True
CREATIONDATE_HIDDEN    = True
COMPLETIONDATE_HIDDEN    = True
DIM_COMPLETE   = True
TODO_STYLE     = 1
AUTOADD_CREATIONDATE = True
AUTOADD_COMPLETIONDATE = True
